### ISSUE TITLE
support docker_container module

### ISSUE THREAD

**Issue by ofercb** [willhallonline/docker-ansible#21]
in order to support docker_container module we need to install Docker SDK for Python
for more information see ansible documentation

https://docs.ansible.com/ansible/latest/modules/docker_container_module.html

**Comment by willhallonline** [comment]
At the moment, I would rather not have to put extra parts into this, mainly as it is not used only for configuring Docker using Ansible, but mainly based around using Ansible. However, feel free to fork and change (it should be pretty easy) and if others are keen I could do it.

I'll leave the issue as open at the moment.

**Comment by Jean-Baptiste-Lasselle** [comment]
> in order to support docker_container module we need to install Docker SDK for Python
> for more information see ansible documentation
> 
> https://docs.ansible.com/ansible/latest/modules/docker_container_module.html

hi @willhallonline maybe what @ofercb could do, is : 
* setting up `ansible`, `python`, and `docker-py` on  a machine i'll call `TARGET_MACHINE`, where the docker builds will happen
* use your ansible setup on his workstation pc, I'll call it `SOURCE_MACHINE`, 
* from `SOURCE_MACHINE`, invoke `ansible`, to execute the  `docker_container` ansible module tasks onthe remote `TARGET_MACHINE`.

I think you should not install `docker-py` in container, in your little framework, because one should **never** build docker images from within a container, that because of the root privileges access vulnerability of docker, and his big fat daemon well known problem. If necessary, see the article of Mr. Petazzoni, on _docker inside docker_ .

Worth mentioning, Petazzoni is the French who created Docker, and funny (i don't know how much) : 
* I just checked on Google for "Who created Docker?" for me not to misspell his name.
* Guess what, Mr. Petazzoni has been wiped out of all of history, Google answers it is "Solomon Hykes" (whoever that is) who founded docker, same for Wikipedia, 
* I just remembered his name suddenly, so I could report that to you. I'll remember,I won't ever work under any american jurisdiction, now when I build a new company, it's going to be mandatory to sign all contracts in several countries, out of any american jurisdiction. Of course, risks will exist in any other country, difference is those country cannot sue me out of their own country, as much as the USA can. And Hi to microsoft new owner of github ;) . That, so I can still work with american people who I love in business.

Mr. Petazzoni 's article on "Docker inside Docker" https://jpetazzo.github.io/2015/09/03/do-not-use-docker-in-docker-for-ci/

Oh, and Will, I wrote this during a long test running on servers, and I wanted to thank you for your `ansible` container, I used it , even if I'm probably going to modify it a lot, to run massive amount of tests, running while I write.  Btw, your websites on side projects are great, i'm currently running massive tests with `hugo` and `ansible` ^^

**Comment by willhallonline** [comment]
@Jean-Baptiste-Lasselle , thanks for all the comments. I will close this issue at the moment. Maybe it will be revisited some time.
