### ISSUE TITLE
cryptography python module require rust compiler

### ISSUE THREAD

**Issue by rayniel95** [willhallonline/docker-ansible#33]
For some reason in ansible 2.9, dockerfile for alpine 3.12, the cryptography module require compilation with rust compiler. Cryptography module is a dependency. Please check https://cryptography.io/en/latest/installation.html#building-cryptography-on-linux .I not sure if this is only "my problem" or a general issue.

**Comment by AzuladoToujours** [comment]
Hello! I've experienced this same issue, trying to build the [alpine version](https://github.com/willhallonline/docker-ansible/blob/master/ansible210/alpine311/Dockerfile) and the  [20.04 of Ubuntu](https://github.com/willhallonline/docker-ansible/blob/master/ansible210/ubuntu2004/Dockerfile). 

There has not been a fix yet, the only one that I could get to build successfully was the [Ubuntu 18.04](https://github.com/willhallonline/docker-ansible/blob/master/ansible210/ubuntu1804/Dockerfile) version, which includes ansiblev2.10.3.
Any update will be appreciated.

**Comment by rayniel95** [comment]
> Hello! I've experienced this same issue, trying to build the [alpine version](https://github.com/willhallonline/docker-ansible/blob/master/ansible210/alpine311/Dockerfile) and the [20.04 of Ubuntu](https://github.com/willhallonline/docker-ansible/blob/master/ansible210/ubuntu2004/Dockerfile).
> 
> There has not been a fix yet, the only one that I could get to build successfully was the [Ubuntu 18.04](https://github.com/willhallonline/docker-ansible/blob/master/ansible210/ubuntu1804/Dockerfile) version, which includes ansiblev2.10.3.
> Any update will be appreciated.

You can modifiy the alpine Dockerfile and build the cryptography python module. Take a look to https://github.com/rayniel95/useful-docker/tree/master/ansible/alpine-plus-python-ansible maybe it help you (delete the proxy line if you will use the Dockerfile).

**Comment by AzuladoToujours** [comment]
Worked like a charm.

**Comment by willhallonline** [comment]
There is a bit more of a thread about this on GitLab (where I actually do most of my build testing). https://gitlab.com/who-docker/docker-ansible/-/merge_requests/2

Older Version OS:
"Alpine 3.11 fails because the new python cryptography module requires rust version over 1.45 so I've deciced to downgrade it to 3.3.2 version which is not using rust. Ubuntu 16.04 failed because pip 21 does not support python 3.5 so I've pinned its version to 20.3.4 too."

Newer Version OS:
Added cargo for build (and required libs) and then removed them after build...
